spring:
  application:
    name: deal
  datasource:
    url: jdbc:postgresql://localhost:5432/deal
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true



server:
  port: 8002
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    displayRequestDuration: true

#spring.flyway.enabled=true
#spring.flyway.clean-disabled=false
