server:
  port:
    8001
  tomcat:
    native: false

spring:
  application:
    name: conveyor
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: false

#logging:
#  level:
#    root: DEBUG
default-rate: 11
default-insurance-price: 100000

exception:
  age-not-allowed: The age of the person receiving the loan must be from 20 to 60 years.
  unemployed: The person receiving the loan must be officially employed.
  excessive-amount: The loan amount should not exceed 20 salaries.
  insufficient-work-experience: The total work experience must be at least 12 months, and the current one must be at least 3 months.

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    displayRequestDuration: true