server:
  port:
    8001
spring:
  application:
    name: conveyor
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging:
  level:
    root: DEBUG
default-rate: 11
exception:
  age-not-allowed: ??????? ????, ??????????? ?????? ?????? ???? ?? 20 ?? 60 ???.
  unemployed: ?????????? ????, ?????????? ??????, ?????? ???? ?????????????.
  excessive-amount: ????? ??????? ?? ?????? ????????? 20 ???????.
  insufficient-work-experience: ????? ???? ?????? ?????? ???? ?? ????? 12 ???????, ? ??????? ???? ?? ?????? 3 ???????.