server:
  port:
    8001
spring:
  application:
    name: conveyor
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging:
  level:
    root: DEBUG
default-rate: 11
exception:
  age-not-allowed: The age of the person receiving the loan must be from 20 to 60 years.
  unemployed: The person receiving the loan must be officially employed.
  excessive-amount: The loan amount should not exceed 20 salaries.
  insufficient-work-experience: The total work experience must be at least 12 months, and the current one must be at least 3 months.