server:
  port: 8000

spring:
  application:
    name: gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: conveyor-service
          uri: http://localhost:8001
          predicates:
            - Path=/conveyor/**
        - id: deal-service
          uri: http://localhost:8002
          predicates:
            - Path=/deal/**
        - id: application-service
          uri: http://localhost:8003
          predicates:
            - Path=/application/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    root: DEBUG
